### PR TITLE
v1.9.4 rollback and Jekyll 4.0 support

### PR DESCRIPTION
**Pull request by letrastudio**
Versions 2.0.0 and 2.1.0 introduced several bugs that affected the Autopages feature. Version 1.9.4 appears to be very stable, working fine even with Jekyll 4.0. With development of the plugin being more or less inactive, I think the most pragmatic solution to get everything working again is to roll back to 1.9.4.

This PR reverts all commits post 1.9.4 and cherry picks the last two, that relaxed the Jekyll dependency version. I've also kept all edits to README.md. All other changes to documentation and examples authored by @ibrado have been reverted, but some might be worth keeping (I didn't have time to check which of them related to 1.9.4).

This might seem like a blunt solution, but it gives us a fully functional version of the plugin that works with Jekyll 4.0, today, with no new code. I suggest releasing this as version 1.9.5, and then resuming development of 2.0.0.

### CODE REVIEW

**Comment by ashmaroli** [comment]
@letrastudio I'm not a maintainer of this project, but provide support nonetheless.

Instead of turning back the pendulum on the `master` branch and moving forward, the best option here is to point your Gemfile to your fork of this project.
You need not touch the `master` branch at all. Just checkout a **new branch from the `v1.9.4` tag** and cherry-pick Jekyll 4.0 support onto that branch.

**Comment by letrastudio** [comment]
@ashmaroli I'm sure you're right and this wasn't the best way of managing the commit history — I'm not that good at Git 😅

And I'm already pointing my Gemfile at this fork, but thanks for suggesting it. I'm just thinking about all the people who might not know that it's an option, and how they may not even *consider* that 1.9.4 is the most stable version to use. (It certainly took me a while to come to that conclusion!)

I could redo this PR the way you mentioned. But do you agree that this is a good idea? Let's not call it a rollback — let's call it a *backport* of Jekyll 4 support to 1.9.x. Wouldn't it be nice to have that hypothetical 1.9.5 version officially released on rubygems?

**Comment by ashmaroli** [comment]
> let's call it a _backport_ of Jekyll 4 support to 1.9.x

That's indeed the correct way of calling this. But unfortunately, this project has just a single branch of code. So technically, *backport PR* wouldn't be possible until there's a `1.9-stable` branch..

**Comment by letrastudio** [comment]
> But unfortunately, this project has just a single branch of code. So technically, _backport PR_ wouldn't be possible until there's a `1.9-stable` branch..

Yeah, I thought that might be the case — that's why I opted for the rollback strategy. My thinking was that after tagging `v1.9.5` the newer changes could then be re-reverted, with the `v1.9.5` tag sitting between `2.1.0` and whatever comes next. Not exactly orthodox, I know…

**Comment by Yuki-Inoue** [comment]
### To whoever who wants to use jekyll 4.0.0 with paginate-v2 1.9.4 features;

I made a fork whose version is based on 1.9.4 but with relaxed dependency, and re-versioned it as 1.9.4.1 .

If you use jekyll under bundler management, then you should be able to update to this version by specifying it in bundler like this;

```
group :jekyll_plugins do
  # ...
  gem 'jekyll-paginate-v2', github: 'Yuki-Inoue/jekyll-paginate-v2', branch: 'maintenance-1.9'
  # ...
end
```

### To maintainer of this repo

Could you release such 1.9.4.1 so that we all can retrieve it from rubygems.org?

**Comment by sverrirs** [comment]
Fixed in https://rubygems.org/gems/jekyll-paginate-v2/versions/3.0.0

**Pull request closed without merging**
