### PR TITLE
reduce the verbosity of pagination logging

### PR DESCRIPTION
**Pull request by mohkale**
by default this plugin logs three lines for autopages. One for tags, collections & categories. It also leaves a line break before logging how many pages have been generated, which breaks the flow of output and doesn't aid in readability very much. This patch fixes these issues.

The blank line outputted before the page log has been erased.

The log for tags, collections and categories has been reduced such that at most 2 lines are output. If all three are available or all three disabled only one line is output.

eg:

```
# tags = enabled, categories = enabled, collections = enabled
>          AutoPages: Generating pages for tags, categories & collections
```

```
# tags = disabled, categories = disabled, collections = disabled
>          AutoPages: tags, categories & collections pages are disabled/not configured in site.config
```

```
# tags = enabled, categories = enabled, collections = disabled
>          AutoPages: Generating pages for tags & categories
>          AutoPages: collections pages are disabled/not configured in site.config
```

I've also added a `silent` option to the users _config.yml file, such that if you've willingly disabled one of the three autopage options, you can stop the plugin from reminding you you've disabled it.

eg:

```yaml
autopages:
  enabled: true

  collections:
    enabled: false
    silent:  true

  categories:
    permalink: /categories/:cat

  tags:
    permalink: /tags/:tag
```

```
# tags = enabled, categories = enabled, collections = disabled
>          AutoPages: Generating pages for tags & categories
```

collections doesn't log anything because you've set silent to true.

### CODE REVIEW

**Comment by mohkale** [comment]
I'm confused, this is the first time I've gotten a notification about this issue since I made it and suddenly there's 49 commits in the backlog. What's going on?

**Comment by mohkale** [comment]
Also, if you don't mind me asking, why was this issue closed? I can't really see any mention of a reason.

**Comment by ashmaroli** [comment]
> suddenly there's 49 commits in the backlog

@mohkale That is because the `base_branch` (`master`) was reset to an older state in Git history. So the commit log here reflects all changes made from that point in the past up until your commit.

Once you rebase the branch onto *current `master`*, all those extra commits will be removed automatically.

**Comment by mohkale** [comment]
Okay, thnx for the clarifications 😄.

I'm still wondering why this pull request was closed? Is this feature not desirable? If I re implemented it on the repository as it is now, would it still be denied?

**Pull request closed without merging**
